"""Chat tools for the ConversationCoachAgent — match context & reply suggestions."""
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from db.models.chat import ChatMessage
from db.models.matching import Match
from db.models.profile import UserProfile
from modules.assistant.tools import current_db, current_user_id


async def get_match_context(match_id: str) -> dict:
    """Get the full conversation context for a match: recent messages and the other user's profile.

    Args:
        match_id: UUID of the match to get context for.

    Returns:
        Dict with other_user (display_name, age, city, bio, hobbies, dating_goal),
        recent_messages (last 10 messages in chronological order),
        and match_info (status, created_at).
    """
    db: AsyncSession | None = current_db.get()
    user_id_str = current_user_id.get()
    if not db or not user_id_str:
        return {"error": "No session context available"}

    user_id = uuid.UUID(user_id_str)
    match = await db.get(Match, uuid.UUID(match_id))
    if match is None or (match.user_a_id != user_id and match.user_b_id != user_id):
        return {"error": "Match not found or access denied"}

    # Get the other user's profile
    other_id = match.user_b_id if match.user_a_id == user_id else match.user_a_id
    profile_result = await db.execute(
        select(UserProfile).where(UserProfile.user_id == other_id)
    )
    profile = profile_result.scalar_one_or_none()

    other_user = {}
    if profile:
        other_user = {
            "display_name": profile.display_name,
            "gender": profile.gender,
            "city": profile.city,
            "dating_goal": profile.dating_goal.value if profile.dating_goal else None,
            "bio": profile.bio,
            "hobbies": profile.hobbies,
            "personality_traits": profile.personality_traits,
            "public_summary": profile.public_summary,
        }

    # Get recent messages
    recent_result = await db.execute(
        select(ChatMessage)
        .where(ChatMessage.match_id == uuid.UUID(match_id))
        .order_by(ChatMessage.created_at.desc())
        .limit(10)
    )
    recent_msgs = list(recent_result.scalars().all())
    recent_msgs.reverse()

    messages = [
        {
            "sender": "me" if msg.sender_user_id == user_id else "them",
            "content": msg.content,
            "created_at": msg.created_at.isoformat() if msg.created_at else None,
        }
        for msg in recent_msgs
    ]

    return {
        "other_user": other_user,
        "recent_messages": messages,
        "match_info": {
            "status": match.status.value if hasattr(match.status, "value") else str(match.status),
            "created_at": match.created_at.isoformat() if match.created_at else None,
        },
    }


async def generate_suggested_replies(match_id: str, tone: str = "natural") -> dict:
    """Generate AI-crafted reply suggestions for a match conversation.

    Looks at the recent chat history with this match, the other person's profile,
    and the requested tone to produce 2-3 natural Vietnamese reply suggestions.
    The agent calling this tool should present the suggestions directly to the user.

    Args:
        match_id: UUID of the match to generate suggestions for.
        tone: Conversation tone — natural, humorous, subtle, proactive, gentle, concise.
              Default is "natural".

    Returns:
        Dict with the match context and a placeholder. The actual suggestions
        are generated by the LLM based on the context returned.
    """
    # This tool fetches context; the LLM (ConversationCoachAgent) uses the context
    # to generate the actual reply suggestions in its response.
    context = await get_match_context(match_id)
    if "error" in context:
        return context

    tone_guide = {
        "natural": "tự nhiên, chân thành, như đang nói chuyện với bạn",
        "humorous": "hài hước, vui vẻ, có chút dí dỏm",
        "subtle": "tinh tế, nhẹ nhàng, ý nhị",
        "proactive": "chủ động, tự tin, trực tiếp rủ rê",
        "gentle": "nhẹ nhàng, lịch sự, ấm áp",
        "concise": "ngắn gọn, súc tích, đi thẳng vào vấn đề",
        "rebel": "bất cần, nổi loạn, không tuân theo quy tắc xã hội, có thể hơi thô lỗ nếu vibe match như vậy",
        "badboy": "bạo lực, không tôn trọng, có thể gây khó chịu nếu vibe match như vậy",
        "sarcastic": "châm biếm, mỉa mai, có thể hơi cay độc nếu vibe match như vậy",
        "flirty": "tán tỉnh, gợi cảm, có chút khiêu khích nếu vibe match như vậy",
        "empathetic": "đồng cảm, thấu hiểu, chia sẻ cảm xúc của match",
        "supportive": "ủng hộ, khích lệ, luôn đứng về phía match",
        "playful": "vui tươi, nghịch ngợm, có chút trẻ con nếu vibe match như vậy",
        "badgirl": "cá tính, mạnh mẽ, không ngại thể hiện quan điểm, có thể hơi thô lỗ nếu vibe match như vậy",
        "sassy": "hỗn xược, tự tin, có phần kiêu căng, có thể gây khó chịu nếu vibe match như vậy",
    }

    return {
        **context,
        "requested_tone": tone,
        "tone_guide": tone_guide.get(tone, tone_guide["natural"]),
        "instruction": (
            f"Dựa vào ngữ cảnh trên, hãy tạo 2-3 câu trả lời gợi ý bằng tiếng Việt "
            f"với tone {tone_guide.get(tone, tone_guide['natural'])}. "
            f"Mỗi câu không quá 35 từ. Đảm bảo phù hợp với ngữ cảnh trò chuyện và "
            f"phong cách của người dùng."
        ),
    }
